### ISSUE TITLE
filter non-xbox controllers

### ISSUE THREAD

**Issue by nevrax** [andrew/node-xbox-controller#30]
some non-xbox contollers (ex: dualshock3 or dualshock4) are detected as native xbox controllers.

![screen shot 2015-03-15 at 00 45 34](https://cloud.githubusercontent.com/assets/684589/6653910/b72f2690-caac-11e4-8c26-74249304790d.png)
if would be nice to have a filtering option.

![img_0002](https://cloud.githubusercontent.com/assets/684589/6653930/f2eaf41a-caad-11e4-8f0f-df2cbcbf1bb3.jpg)

also it would be great if i could use multiple xbox controllers for a multi player setup.

**Comment by nevrax** [comment]
according to HID.devices() we could use the serialNumber
 * to filter a specific controller
```
var myController = new XboxController('70623960');
```
 * to init multiple controllers
```
var player1 = new XboxController('A4DE0760');
var player2 = new XboxController('70623960');
```
all devices
```
[ { vendorId: 1118,
    productId: 654,
    path: 'Wireless_045e_028e_4100002',
    serialNumber: 'A4DE0760',
    manufacturer: 'Microsoft',
    product: 'Wireless 360 Controller',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 5 },
  { vendorId: 1118,
    productId: 654,
    path: 'Wireless_045e_028e_4100001',
    serialNumber: '70623960',
    manufacturer: 'Microsoft',
    product: 'Wireless 360 Controller',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 5 } ]
```
that's also valid for DualShock controllers
(note: the Unknown manufacturer is actually Sony (DS4)
```
[ { vendorId: 1356,
    productId: 616,
    path: 'Bluetooth_054c_0268_75517eb7',
    serialNumber: '00-06-f5-51-7e-b7',
    manufacturer: 'Sony',
    product: 'PLAYSTATION(R)3 Controller',
    release: 256,
    interface: -1,
    usagePage: 1,
    usage: 4 } ]
[ { vendorId: 1356,
    productId: 1476,
    path: 'Bluetooth_054c_05c4_5aad1995',
    serialNumber: '1c-96-5a-ad-19-95',
    manufacturer: 'Unknown',
    product: 'Wireless Controller',
    release: 256,
    interface: -1,
    usagePage: 1,
    usage: 5 } ]
```
something similar was already coded by @barisbalic on [multiple-controllers](https://github.com/andrew/node-xbox-controller/tree/multiple-controllers) branch.

it would be great to have this commit https://github.com/andrew/node-xbox-controller/commit/d910af8a7e91d5f4c4e5c3be3a16583ea661849e tested and merged into master branch.

thank you!

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
