### ISSUE TITLE
Update to node-hid 

### ISSUE THREAD

**Issue by gordonturner** [andrew/node-xbox-controller#33]
Hey,

FYI, node-hid is now fixed and is at v0.4.0:

https://github.com/node-hid/node-hid/issues/90#issuecomment-105690579

Would it be possible to update the dependency?

Thanks!
Gord.

**Comment by andrew** [comment]
@gordonturner can you give this branch a try, if it's working I'll merge it and publish a new version to npm: https://github.com/andrew/node-xbox-controller/pull/34

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
