### ISSUE TITLE
list of all available events for `xbox.on()`

### ISSUE THREAD

**Issue by cschell** [andrew/node-xbox-controller#35]
I'm having a hard time to understand all the events that are available for `xbox.on()`. There are, obviously, those listed in the Readme (like `lefttrigger` or `right:move`), but I also saw `rightshoulder:release` used by [xbox-parrot](https://github.com/cschell/xbox-parrot).

I've yet to find a complete list of all available events and couldn't find anything helpful in the resources mentioned on top of the readme. So probably it's terribly obvious and I'm just missing it, but is there such a list anywhere?

**Comment by andrew** [comment]
The full list of buttons is in this file: https://github.com/andrew/node-xbox-controller/blob/master/lib/buttons.json

We should add those to the readme as well

**Comment by cschell** [comment]
That would be great :) Maybe that then could be referenced to a graphic [like that](https://en.wikipedia.org/wiki/Xbox_360_Controller#/media/File:360_controller.svg), so everyone knows what's what.

**Comment by gordonturnerolson** [comment]
FYI, I added all (I think?) to the example.js, check it out:
 [https://github.com/andrew/node-xbox-controller/blob/master/example.js](https://github.com/andrew/node-xbox-controller/blob/master/example.js).

**Comment by andrew** [comment]
Ah yes, good point @gordonturnerolson, I've linked to the example in the readme now: https://github.com/andrew/node-xbox-controller/commit/9b8340b67fec7df55e212b33590e56367e1afc61

**Comment by gordonturner** [comment]
Doh, that was my  corporate alter ego commenting there...

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
