### ISSUE TITLE
Can't find Xbox controller on refresh

### ISSUE THREAD

**Issue by electrovir** [andrew/node-xbox-controller#64]
I'm experimenting with using this within a NW.js project.  I've discovered that if I reload the window in NW.js, my Xbox controller can no longer be found.  If I quit NW.js completely and relaunch it, then it works just fine again.

I noticed that after reloading, my xbox object has an hid property set to false, rather than an object.

**Comment by andrew** [comment]
I'm not sure how to fix this, might be a bug in the underlying HID module

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
