### ISSUE TITLE
Problems on windows

### ISSUE THREAD

**Issue by jieverson** [andrew/node-xbox-controller#74]
Been used with Win10 and a xBox Controller. Controller is been detected, but console is logging serial number as _undefined_.  Buttons are been fired wrong. When presses A or B, left stick events are fires. When moved L-stick, A button press/release events are fired. Tried call lib configuration, but it is not working well too.

**Comment by jonathanprl** [comment]
Same here.

**Comment by andrew** [comment]
@jieverson @jonathanprl sorry I don't have access to a windows 10 machine to test it on

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
